import Link from "next/link";
import { ArrowRight, BadgeCheck, Building2, HandCoins, Leaf, ShieldCheck, Sprout, Users, WalletCards } from "lucide-react";
import { PublicShell, L } from "@/components/public-shell";
import { publicData } from "@/lib/data";

export const dynamic="force-dynamic";
export default async function Home({searchParams}:{searchParams:Promise<{lang?:string}>}){
 const lang=(await searchParams).lang==='en'?'en':'ne'; const d=await publicData(); const obj=d.objectives; const q=lang==='en'?'?lang=en':'';
 return <PublicShell lang={lang}><main>
  <section className="hero-pattern overflow-hidden"><div className="mx-auto grid max-w-7xl items-center gap-12 px-4 py-16 lg:grid-cols-[1.1fr_.9fr] lg:py-24"><div><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-emerald-200 bg-white px-4 py-2 text-sm font-semibold text-[#0c644e]"><BadgeCheck size={17}/><L ne="वि.सं. २०६८ सालदेखि सेवामा" en="Serving since 2068 B.S." lang={lang}/></div><h1 className="max-w-4xl text-4xl font-extrabold leading-tight text-[#103c32] sm:text-6xl"><L ne={d.sections.hero.titleNe} en={d.sections.hero.titleEn} lang={lang}/></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600"><L ne={d.sections.hero.contentNe} en={d.sections.hero.contentEn} lang={lang}/></p><div className="mt-9 flex flex-wrap gap-3"><Link className="btn-primary" href={'/contact'+q}><L ne="सदस्य बन्नुहोस्" en="Become a Member" lang={lang}/><ArrowRight size={18}/></Link><Link className="btn-secondary" href={'/savings'+q}><L ne="बचत सुरु गर्नुहोस्" en="Start Saving" lang={lang}/></Link></div></div><div className="relative"><div className="rounded-[2rem] bg-[#0d5643] p-8 text-white shadow-2xl sm:p-12"><div className="mb-10 grid h-16 w-16 place-items-center rounded-2xl bg-amber-400 text-[#123d32]"><Sprout size={34}/></div><p className="text-sm uppercase tracking-[.2em] text-emerald-200"><L ne="सहकारीको प्रतिबद्धता" en="Our commitment" lang={lang}/></p><h2 className="mt-3 text-3xl font-bold"><L ne="सदस्यको हित, समुदायको समृद्धि" en="Member welfare, community prosperity" lang={lang}/></h2><div className="mt-10 grid grid-cols-2 gap-4 border-t border-white/20 pt-6 text-sm"><span><strong className="block text-xl">६</strong><L ne="सेवाहरू" en="Services" lang={lang}/></span><span><strong className="block text-xl">२</strong><L ne="सेवा स्थान" en="Service locations" lang={lang}/></span></div></div></div></div></section>
  <section className="section"><div className="grid gap-12 lg:grid-cols-2"><div><p className="eyebrow"><L ne="हाम्रो परिचय" en="Who we are" lang={lang}/></p><h2 className="section-title"><L ne={d.sections.about.titleNe} en={d.sections.about.titleEn} lang={lang}/></h2><p className="mt-6 text-lg leading-9 text-slate-600"><L ne={d.sections.about.contentNe} en={d.sections.about.contentEn} lang={lang}/></p><Link className="mt-7 inline-flex items-center gap-2 font-bold text-[#08755b]" href={'/about'+q}><L ne="विस्तृत पढ्नुहोस्" en="Read more" lang={lang}/><ArrowRight size={18}/></Link></div><div className="rounded-3xl border bg-white p-7 shadow-sm"><h3 className="mb-6 text-xl font-bold text-[#103c32]"><L ne="हाम्रा उद्देश्यहरू" en="Our objectives" lang={lang}/></h3><ul className="space-y-4">{obj.map(x=><li key={x.id} className="flex gap-3"><span className="mt-1 grid h-6 w-6 shrink-0 place-items-center rounded-full bg-emerald-100 text-emerald-700">✓</span><L ne={x.textNe} en={x.textEn} lang={lang}/></li>)}</ul></div></div></section>
  <section className="bg-[#103c32] py-20 text-white"><div className="section py-0"><p className="eyebrow text-amber-300"><L ne="हाम्रा सेवाहरू" en="Our services" lang={lang}/></p><div className="flex items-end justify-between"><h2 className="section-title text-white"><L ne="तपाईंको आर्थिक यात्रामा साथ" en="Alongside your financial journey" lang={lang}/></h2><Link href={'/services'+q} className="hidden text-sm font-bold sm:block"><L ne="सबै हेर्नुहोस् →" en="View all →" lang={lang}/></Link></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{d.services.map((x,i)=><article key={x.id} className="rounded-2xl border border-white/10 bg-white/5 p-6 transition hover:bg-white/10"><span className="mb-5 grid h-11 w-11 place-items-center rounded-xl bg-amber-400 text-[#103c32]">{i%2?<HandCoins/>:<WalletCards/>}</span><h3 className="text-xl font-bold"><L ne={x.nameNe} en={x.nameEn} lang={lang}/></h3><p className="mt-3 text-sm leading-6 text-emerald-100/75"><L ne={x.descriptionNe} en={x.descriptionEn} lang={lang}/></p></article>)}</div></div></section>
  <section className="section"><p className="eyebrow"><L ne="बचत योजना" en="Savings plans" lang={lang}/></p><h2 className="section-title"><L ne="आजको बचत, भोलिको आधार" en="Save today for tomorrow" lang={lang}/></h2><div className="mt-10 grid gap-6 lg:grid-cols-3">{d.savings.map(x=><article className="card" key={x.id}><div className="mb-5 flex items-center justify-between"><span className="icon-box"><Leaf/></span><span className="text-sm font-semibold text-amber-700"><L ne={x.durationNe||''} en={x.durationEn||''} lang={lang}/></span></div><h3 className="text-xl font-bold text-[#103c32]"><L ne={x.nameNe} en={x.nameEn} lang={lang}/></h3><p className="mt-3 min-h-12 text-sm text-slate-600"><L ne={x.descriptionNe} en={x.descriptionEn} lang={lang}/></p><div className="mt-5 space-y-2 border-t pt-4">{x.rates.slice(0,3).map((r,i)=><div key={i} className="flex justify-between gap-3 text-sm"><span><L ne={r.labelNe} en={r.labelEn} lang={lang}/></span><strong className="text-right"><L ne={r.valueNe} en={r.valueEn} lang={lang}/></strong></div>)}</div></article>)}</div></section>
  <section className="border-y bg-white"><div className="section"><div className="grid items-center gap-12 lg:grid-cols-[.8fr_1.2fr]"><div className="rounded-3xl bg-amber-50 p-9"><ShieldCheck className="text-amber-700" size={48}/><h2 className="mt-6 text-3xl font-bold text-[#103c32]"><L ne="किन हामीलाई रोज्ने?" en="Why choose us?" lang={lang}/></h2><p className="mt-4 text-slate-600"><L ne="पारदर्शी व्यवस्थापन र सदस्यमैत्री सेवाप्रति हाम्रो प्रतिबद्धता।" en="Our commitment to transparent management and member-friendly service." lang={lang}/></p></div><div className="grid gap-4 sm:grid-cols-2">{[['सुरक्षित बचत','Secure savings'],['सहुलियतपूर्ण कर्जा','Concessional loans'],['छिटो सेवा','Prompt service'],['पारदर्शी व्यवस्थापन','Transparent management'],['अनुभवी कर्मचारी','Experienced staff'],['सदस्यमैत्री सेवा','Member-friendly service']].map((x,i)=><div key={i} className="flex items-center gap-4 rounded-xl border p-4"><BadgeCheck className="text-emerald-600"/><strong><L ne={x[0]} en={x[1]} lang={lang}/></strong></div>)}</div></div></div></section>
  <section className="section"><div className="grid gap-8 lg:grid-cols-3"><div className="lg:col-span-2"><p className="eyebrow"><L ne="कर्जा सेवा" en="Loan products" lang={lang}/></p><h2 className="section-title"><L ne="उद्यम र अवसरका लागि सहयोग" en="Support for enterprise and opportunity" lang={lang}/></h2><div className="mt-8 grid gap-4 sm:grid-cols-3">{d.loans.map(x=><Link href={'/loans'+q} key={x.id} className="card group"><HandCoins className="text-emerald-700"/><h3 className="mt-5 font-bold group-hover:text-emerald-700"><L ne={x.nameNe} en={x.nameEn} lang={lang}/></h3><p className="mt-2 text-xs text-slate-500"><L ne="विवरणका लागि हेर्नुहोस्" en="View details" lang={lang}/></p></Link>)}</div></div><aside className="rounded-3xl bg-[#eaf3ef] p-8"><Users size={40} className="text-[#08755b]"/><p className="eyebrow mt-7"><L ne="अध्यक्षको सन्देश" en="Chairman's message" lang={lang}/></p><blockquote className="mt-3 text-lg leading-8 text-slate-700"><L ne={d.sections.chairman.contentNe} en={d.sections.chairman.contentEn} lang={lang}/></blockquote><strong className="mt-6 block text-[#103c32]">राज कुमार प्रसाद पाल</strong><a className="mt-1 block text-sm text-emerald-700" href="tel:9829458061">9829458061</a></aside></div></section>
  <section className="section"><div className="rounded-[2rem] bg-[#0d5643] px-6 py-12 text-center text-white sm:px-12"><Building2 className="mx-auto text-amber-300" size={44}/><h2 className="mx-auto mt-5 max-w-2xl text-3xl font-bold"><L ne="सहकारी सेवाबारे थप जानकारी चाहनुहुन्छ?" en="Need more information about our cooperative services?" lang={lang}/></h2><p className="mt-4 text-emerald-100"><L ne="हाम्रो टोलीसँग सम्पर्क गर्नुहोस्।" en="Get in touch with our team." lang={lang}/></p><Link className="mt-7 inline-flex rounded-xl bg-amber-400 px-6 py-3 font-bold text-[#103c32]" href={'/contact'+q}><L ne="सम्पर्क गर्नुहोस्" en="Contact Us" lang={lang}/></Link></div></section>
 </main></PublicShell>
}
